### ISSUE TITLE
libary sucks

### ISSUE THREAD

**Issue by ooor28** [pyrevolt/pyrevolt#9]
lmao spaghetti code
dosent even work
i couldnt even fix it
thats how shit ur libary is

**Comment by GenericNerd** [comment]
Going to need a bit more information than this. Can you provide a traceback or a sample of code to debug and find the cause to the issue?

**Comment by GenericNerd** [comment]
Spoke to @otiopo over Discord.
According to the user, they attempted to install the library to Python version 3.8.12 (via Replit).
This version is not supported, so this issue is not valid.
